### ISSUE TITLE
adding new features & solver setting

### ISSUE THREAD

**Issue by Saeid3** [jvail/glpk.js#16]
There are some important features in the original glpk that is not present in this repo. I understand the plan is to keep it simple but I think a couple of features worth adding.

- glpk.js doesn't return shadow price information in LP problems.
- we can't pass any solver setting such as `tmLim` or `mipGap` to control the solution procedure. 

I forked this repo (https://github.com/TakeScoop/glpk.js) and tried to address these issues. I added shadow prices to the output of LP solutions. I also added an object of solver settings to the API with values of `mipGap`, `tmLim` & `msgLev` which are the important ones. 
I pass these settings as function args in `glpk.js.c` hardcoded. A better way would be to create an object of these settings in js and pass it to the `solve_mip`, but I couldn't manage to do it.

If these changes that I made are cool, I can create a PR to merge them back here.

cc. @rregue

**Comment by jvail** [comment]
Hi @Saeid3, sure, thank you. Please file a PR into the dev branch. There might be a few thing I'd like to discuss with you.

**Comment by Saeid3** [comment]
Great! I created PR https://github.com/jvail/glpk.js/pull/17
