### ISSUE TITLE
Trying to use WebAssembly version in vuejs

### ISSUE THREAD

**Issue by jdemoort** [jvail/glpk.js#2]
Hi,

I'm trying to run the glpk example in vuejs but run into:
  Uncaught (in promise) TypeError: glpk.solve is not a function 
Any ideas? Would this indicate the .wasm file is not loaded?

>> Was indeed the case. This can be closed
>> sorry for the confusion

Many thanks in advance,
-Jan

**Comment by jvail** [comment]
Hi

I guess you tried the spatialite vue example and replaced it with glpk. Did you try `my_glpk_import.then(glpk => glpk.solve(lp))` ? Or could you post your solution if it does work now?

Jan

**Comment by jdemoort** [comment]
No, probably should have looked into that example first :-)

As a temporary solution to move forward, I ended up editing the glpk.js file to fix the path to the glpk.wasm file. I will look further into the spatialite vue example this week to come to a clean solution. (I'm using nuxtjs + vuejs)

Best,
-Jan

**Comment by jvail** [comment]
Ok, good. If you have a snippet or a suggestion just let me know. The combination of an async. loaded wasm + worker + bundler is quite annoying and I am not sure if there is a solution to make it work out of the box everywhere.

**Comment by jvail** [comment]
...
