### ISSUE TITLE
Allow setting "shift" for objective

### ISSUE THREAD

**Issue by drproktor** [jvail/glpk.js#24]
Currently setting the "shift" does not seem to be supported from glpk.js. This can be added via the `glp_set_obj_coef` function with the index `j == 0`. See also the glpk documentation on the  `glp_set_obj_coef` function. It could be added e.g. by giving the objective object a const element next to the vars array.

**Comment by jvail** [comment]
Hi, someone requested that in issue #3 but never replied. Frankly, I do not understand why it is necessary. Could you try to explain why you would like to add this feature?

**Comment by drproktor** [comment]
You are right. It does not give you any advantage because the min/max objective will only be shifted. From my understanding the solution will be independent of the shift. I am not an expert on linear programming and referred to the original documentation of glpk. As my objective contained such a shift I wanted to add it first, but this is not necessary.
