### ISSUE TITLE
Update to GLPK 5

### ISSUE THREAD

**Issue by jvail** [jvail/glpk.js#25]

**Comment by rregue** [comment]
Addressed in https://github.com/jvail/glpk.js/pull/27

**Comment by jvail** [comment]
> Addressed in #27

Almost :) This one is related to the next major release where I'd like to replace the glpk source download with a submodule (https://salsa.debian.org/science-team/glpk.git). See branch `v4` (far from done).

I think I will soon have spare time to work on this so I wonder if you'd like to share your thoughts on the new "design/api" since you seem to have a project using glpk.
Apart from using a submodule fro glpk sources the largest change I'd like to make is bundling (compressed) web-worker and wasm code in one file (base64): Here is an example from another project: https://github.com/jvail/plantgl-jupyter/blob/master/src/pgljs/src/index.js

I found it very convenient to import only one (large) file.

**Comment by rregue** [comment]
I see, this makes total sense. I have never used submodules before but they seem a great fit for this case. 
I am no longer involved with the project that was using glpk, but I had some spare time, I saw some of the opened issues and thought I will contribute. The project I was working on was backend only and this library worked great for us. The interface was very clean, much simpler than the node-glpk. 
Some of the minor issues we had when we transitioned to this package were around being able to pass more options to the solver and shipping the internal logs generated by glpk in the format we wanted. 

Passing more options makes it easier to test and experiment with different algorithms or settings, mostly around cuts, which could be a great add for educational purposes if someone wants to build a web app around optimization and linear programming.

**Comment by jvail** [comment]
Appreciate your contributions.

> The project I was working on was backend only and this library worked great for us.

All right, then you weren't bothered by the worker/wasm file issue. I think for nodejs we can keep the wasm file separately.

**Comment by jvail** [comment]
> Passing more options makes it easier to test and experiment with different algorithms or settings, mostly around cuts, which could be a great add for educational purposes if someone wants to build a web app around optimization and linear programming.

Yes, I agree. I thought about having a second build option that exposes a lot more options from GLPK especially reading/writing LP formats since you can not really model LPs in JSON.  But that might be a bit out of scope for this tiny project.
