### ISSUE TITLE
shift term

### ISSUE THREAD

**Issue by Terrodar** [jvail/glpk.js#3]
Hello! how can I include the shift term in the model?

for example:  **max z = x1 + x2 + 10**

I want to include the **10** constant in the model

Thanks!

**Comment by jvail** [comment]
Hi, I am not an LP expert but I'd guess that adding a constant term to the objective function would not make any difference and the result is the same. It is like solving the LP and adding 10 to the resulting z.

**Comment by jvail** [comment]
...
