### ISSUE TITLE
Possible to use CBC instead of GLPK?

### ISSUE THREAD

**Issue by xiaohk** [jvail/glpk.js#30]
Hello @jvail, this package is so cool and helpful! I love the idea to use JSON interface to interact with LP solvers! Really appreciate your effort in making and maintaining it! 🤩

If I understand it correctly, this package compiles the GLPK source code from C to wasm, and then calls the wasm using webWorker from JS with user's JSON specifications. If the JS is calling from the browser, it decodes the wasm base64 string first.

I am wondering if it is possible to use [CBC](https://projects.coin-or.org/Cbc) instead of GLPK for the backend solver? I am asking because CBC has a more permissive license (Eclipse Public License) comparing to GLPK (GPL). I heard CBC is faster than GLPK too.

**Comment by jvail** [comment]
Hello @xiaohk, thank you. Would be interesting to compare both in terms of speed and api. If the features both libs offer are identical then I am not so sure if it would make sense to offer a second backend. However creating another JS port for CBC (cbc.js ?) with a similar JSON interface should not be too difficult. I just don't know if I have time for it - for sure I could help if you would like to reuse the glpk.js code to wrap CBC.
Regarding the GPL license there are some thoughts over here https://observablehq.com/@tomlarkworthy/mip - maybe helpful.

**Comment by xiaohk** [comment]
Thank you, @jvail! Sounds good, I will let you know if I try to use glpk.js code to wrap CBC.

**Comment by dberardo-com** [comment]
@xiaohk  let us know, i might join the forces too
