### ISSUE TITLE
Is there a way to deconstruct WASM objects?

### ISSUE THREAD

**Issue by xiaohk** [jvail/glpk.js#31]
Hello, in my project I need to solve many linear programming models in one run. When I solve too many models, I encounter the error below. It seems it is caused by the internal WASM program running out of memory. I am wondering if there is a way to deconstruct/release the glpk internal WASM after I solve each model?

```
TypeError: Cannot perform Construct on a detached ArrayBuffer

RuntimeError: abort(TypeError: Cannot perform Construct on a detached ArrayBuffer). Build with -s ASSERTIONS=1 for more info.
    at process.V (/Users/JayWong/[myfile].js:700:13)
    at process.emit (events.js:400:28)
    at processPromiseRejections (internal/process/promises.js:245:33)
    at processTicksAndRejections (internal/process/task_queues.js:96:32)
```

**Comment by jvail** [comment]
Hi @xiaohk, thanks for the example. I have never had a memory issue even with large LPs so I will definitely try to fix this one if I can find the issue. Maybe there were changes in the current emscripten regarding memory handling that I am was not aware of when I made the new release.
