### ISSUE TITLE
Problem with very simple model (square 2x2)

### ISSUE THREAD

**Issue by Daniel-Alievsky** [jvail/glpk.js#35]
Hello!

I've tried to test this library with a very simple situation: square 2x2, from -1.0 to 1.0 by both coordinates. I've corrected your lp.html test by replacing lp model:
```
const lp = {
                    name: 'LP',
                    objective: {
                        direction: glpk.GLP_MIN,
                        name: 'obj',
                        vars: [
                            { name: 'x1', coef: 1 },
                            { name: 'x2', coef: 1 }
                        ]
                    },
                    subjectTo: [
                        {
                        name: 'cons1',
                            vars: [
                                { name: 'x1', coef: 1.0 },
                                { name: 'x2', coef: 0.0 }
                            ],
                            bnds: { type: glpk.GLP_DB, ub: 1.0, lb: -1.0 }
                        },
                        {
                            name: 'cons2',
                            vars: [
                                { name: 'x1', coef: 0.0 },
                                { name: 'x2', coef: 1.0 }
                            ],
                            bnds: { type: glpk.GLP_DB, ub: 1.0, lb: -1.0 }
                        }
                    ]
                };
```
Of course, minimum of x1+x2 in such a square is at point (-1,-1). But your script prints:
```


{
  "name": "LP",
  "time": 0.001,
  "result": {
    "vars": {
      "x1": 0,
      "x2": 0
    },
    "dual": {
      "cons1": 0,
      "cons2": 0
    },
    "z": 0,
    "status": 5
  }
}

\* Problem: LP *\

Minimize
 obj: + x1 + x2

Subject To
 cons1: + x1 - ~r_1 = -1
 cons2: + x2 - ~r_2 = -1

Bounds
 0 <= ~r_1 <= 2
 0 <= ~r_2 <= 2

End
```
What does it mean? Copy of the the corrected lp.html script is attached in the zip
Moreover, I don't understand ~r_1 and ~r_2 in your problem description. I tried to specify both boundaries: -1 <= x1/x2 <= 1.

[lp.zip](https://github.com/jvail/glpk.js/files/8808719/lp.zip)

**Comment by jvail** [comment]
Hi @Daniel-Alievsky,

I think discussion on non-negativity might help: https://github.com/jvail/glpk.js/issues/29

This part 

```
\* Problem: LP *\

Minimize
 obj: + x1 + x2

Subject To
 cons1: + x1 - ~r_1 = -1
 cons2: + x2 - ~r_2 = -1

Bounds
 0 <= ~r_1 <= 2
 0 <= ~r_2 <= 2

End
```

is the LP printed in one of the GLPK supported formats, You can put it in a text file and run it with GLPSOL to verify the result against glpk.js. What does it yield?

**Comment by Daniel-Alievsky** [comment]
Thank you. I've really forgot that LP problem is usually solved for non-negative variables. Not a problem, if the user learned this in university, but not obvious for end-user, which just want to optimize some condition with linear constraints. Maybe you will add a few word to the main page - namely, that all variables are supposed to be >= 0.0?

Then, it seem I understand the sense of ~r_1 / ~r_2. They are new variables, added to resolve task with range constraint like 
a <= x <= b
It is equivalent to solving task
x - ~r = a
0 <= ~r <= b-a
Right?

**Comment by Daniel-Alievsky** [comment]
Also a little question, if possible. Where can I find source code of your JavaScript solver? Or it is not provided? In this GitHub I've found only a few service code in "src" directory and packed JavaScript in "dist".

**Comment by jvail** [comment]
> Thank you. I've really forgot that LP problem is usually solved for non-negative variables. Not a problem, if the user learned this in university, but not obvious for end-user, which just want to optimize some condition with linear constraints. Maybe you will add a few word to the main page - namely, that all variables are supposed to be >= 0.0?

Yes, LP design can be quite complicated and there are lots of "work-around" recipes for problems you can not directly model in a LP. But this is not specific for GLPK.

> Also a little question, if possible. Where can I find source code of your JavaScript solver? Or it is not provided? In this GitHub I've found only a few service code in "src" directory and packed JavaScript in "dist".

It is not a JS solver. It is just a wrapper around a solver (GLPK) written in c. There is a git submodule with a link to the solver source code: https://github.com/jvail/glpk.js/blob/master/.gitmodules
