### ISSUE TITLE
GLPK.GLP_FR potentially undefined (also: allowing non-negative variables)

### ISSUE THREAD

**Issue by sikoried** [jvail/glpk.js#36]
For some reason, `GLPK.GLP_FR` is undefined. MWE is along the lines of the provided `lp.html` example

```javascript
import GLPK from '../dist/glpk.js';
(async () => {
    const glpk = await GLPK();
    console.log(GLPK.GLP_FR); // "undefined"
})();
```

I ran into this when working with negative variables, as discussed in #29 . Through working with `glpsol` and converting MathProg problems into CPLEX files, I observed, that `glpsol --wlp` would include a `Bounds` section that labels the appropriate variables as `free`, effectively dropping the non-negativity constraint.

Setting the `bounds` field in the (javascript) `lp` definition by including appropriate `{name: 'my_var', type: 1}` (i.e. the value, `GLPK.GLP_FR` is supposed to be) objects fixed the issue.

PS: Thanks for this great wrapper library!

**Comment by jvail** [comment]
Hi @sikoried,

could you try `glpk.GLP_FR`? The thing is that the async (worker) version has those flags attached to the glpk instance rather than the GLPK import. Sorry, that might be a bit confusing ... I do not recall exactly why but I think I introduced the worker/async version later.

Jan

**Comment by sikoried** [comment]
Yes this works. Now that I look at it, I had used the instance further up in my code...

However, maybe you could add my note above (re negative variables) to your readme :-)

**Comment by jvail** [comment]
> However, maybe you could add my note above (re negative variables) to your readme :-)

Sure, I did not look it up in the GLPK docs but could you create a complete, little example demonstrating the use of `GLP_FR` and non-negativity?
