### ISSUE TITLE
Size issues

### ISSUE THREAD

**Issue by wetneb** [jvail/glpk.js#4]
This library is fantastic, it is very pleasant to use.

One thing I am a bit worried about is the size of the library, 1.05 MB according to webpack.
If I understand correctly, the entire glpk library is included in the package, even if the interface it exposes might not use all of glpk itself.

If this is correct, how hard would it be to trim down the WebAssembly to only the code that is required for the interface exposed? It sounds quite hard to me.

Are you aware of any JS library exposing a similar interface, but with a lighter memory footprint (possibly to the expense of speed)?

**Comment by jvail** [comment]
Hi, happy you find it useful. Actually the wasm file is "just" ~ 470 KiB. But I have not tested a build with the latest emscripten version - might further reduce the size. Or maybe you confused it with https://github.com/hgourvest/glpk.js/blob/master/dist/glpk.js?
Yes, emscripten will strip all unused code (functions not exposed to JS) from the build.

**Comment by wetneb** [comment]
Wow, nice! I had no idea emscripten did that.

> Actually the wasm file is "just" ~ 470 KiB.

Ok. I am a total wasm noob, but [the npm package is reported to be 2.3MB big in total](https://www.npmjs.com/package/glpk.js). Not sure where the rest is coming from?

> Or maybe you confused it with https://github.com/hgourvest/glpk.js/blob/master/dist/glpk.js?

No I am definitely using yours. I am listed in the [used by](https://github.com/jvail/glpk.js/network/dependents?package_id=UGFja2FnZS00MjIyMzkzNw%3D%3D) section.

> I have not tested a build with the latest emscripten version - might further reduce the size.

If you ever get a chance, it would be nice. I would try myself but I have no idea how! :)

**Comment by jvail** [comment]
I think I have several builds included there: e.g. node & webworker
Emscripten is actually very well documented: https://emscripten.org/docs/getting_started/downloads.html
If you have installed the sdk and setup your PATH then in the glpk.js source you just run "make" - and in theory it should build.
Give it a try :) If you can reduce the size with the latest emscripten I am happy to update the npm package.

**Comment by wetneb** [comment]
> I think I have several builds included there: e.g. node & webworker

When including glpk.js as a dependency with webpack, is there a way to specify only a specific build to be included in the bundle? (Or is that also something that is already done behind my back?)

> Give it a try :) If you can reduce the size with the latest emscripten I am happy to update the npm package.

Just tried with a stock emscripten packaged for Debian (probably not the best way to get the bleeding edge version) and it fails like this:

```
em++ -O3 --memory-init-file 0  -s INLINING_LIMIT=50 -s RETAIN_COMPILER_SETTINGS=1 -s EXPORTED_FUNCTIONS="[ '_glp_version', '_glp_create_prob', '_glp_erase_prob', '_glp_delete_prob', '_glp_create_index', '_glp_set_prob_name', '_glp_get_prob_name', '_glp_set_obj_dir', '_glp_find_col', '_glp_set_col_bnds', '_glp_set_row_bnds', '_glp_set_obj_coef', '_glp_add_rows', '_glp_add_cols', '_glp_set_row_name', '_glp_set_col_name', '_glp_set_mat_row', '_glp_set_col_kind', '_glp_get_col_lb', '_glp_get_col_ub', '_glp_delete_index', '_glp_sort_matrix', '_glp_get_num_int', '_glp_get_num_bin', '_glp_get_num_cols', '_glp_init_iocp', '_glp_mip_obj_val', '_glp_mip_status', '_glp_get_col_name', '_glp_mip_col_val', '_glp_init_smcp', '_glp_get_obj_val', '_glp_get_status', '_glp_get_col_prim', '_glp_delete_prob', '_glp_free_env', '_glp_write_lp', '_solve_lp', '_solve_mip' ]" -s ALLOW_MEMORY_GROWTH=1 \
-Isrc/glpk/glpk-4.65/src -Isrc/glpk/glpk-4.65/src/bflib \
-Isrc/glpk/glpk-4.65/src/env -Isrc/glpk/glpk-4.65/src/misc \
--pre-js src/pre.js --post-js src/post.js  \
bc/glpk.bc src/glpk.js.c -o glpk.js \

WARNING  root: Disabling asm.js validation for memory growth (memory can grow, but you lose some amount of speed)
clang: warning: treating 'c' input as 'c++' when in C++ mode, this behavior is deprecated [-Wdeprecated]
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 392, in _handle_results
    task = get()
TypeError: __init__() takes at least 3 arguments (1 given)

```

**Comment by jvail** [comment]
hm, I'd guess it is an outdated emsdk version.

**Comment by wetneb** [comment]
Ok, then there is probably not much to improve, so I propose we just close this.

**Comment by jvail** [comment]
There is always something to improve - size? Not sure. But I have seen that you are using an old version in https://github.com/wetneb/sheetshow/blob/master/package.json#L8. That is a pure JS build and indeed quite large.

**Comment by wetneb** [comment]
Oh, my bad. It should obviously be much better. Thanks a lot!
