### ISSUE TITLE
Need help modelling a simple(?) battery charge problem

### ISSUE THREAD

**Issue by gruijter** [jvail/glpk.js#42]
I have no clue how to do this. I tried the following, but it results in the battery being charged higher then the capacity.
This is the problem:
I want an optimum charge/discharge scheme for my battery. In this example I have 8 hours, and in each hour the cost of energy varies. I start with an empty battery. I want to end with maximum profit (=minimum cost)

the State of Charge (SoC) of the battery can never exceed 5kWh, and has a minimum of 0. The battery can be loaded with a maximum of 2kW, and discharged with a maximum of 1.7kW.

```
const GLPK = require('glpk.js');
const glpk = GLPK();
const options = {
    msglev: glpk.GLP_MSG_ALL,
    presol: true,
    cb: {
        call: progress => console.log(progress),
        each: 1
    }
};

const maxSoC = 5; // kWh
const minSoC = 0; // kWh
const maxCharge = 2; // kW
const minCharge = -1.7; // kW (negative is discharging)

const startSoC = 0; // kWh (when 0, the battery is empty at start)
const prices = [ 0.1, 0.1, 0.2, 0.2, 0.3, 0.3, 0.5, 0.5, 0.5]; // prices per kWh for each hour

// optimized load per hour l1..l8 is what is being looked for
// objective function (minimize cost) totalCost = l1*p1 + l2*p2 + ... + l8*p8
// the State of Charge (SoC) of the battery can never exceed 5, and has a minimum of 0.


const toSolve = {
    name: 'LP',
    objective: {
        direction: glpk.GLP_MIN,
        name: 'totalCost',
        vars: [
            { name: 'l1', coef: prices[0] },
            { name: 'l2', coef: prices[1] },
            { name: 'l3', coef: prices[2] },
            { name: 'l4', coef: prices[3] },
            { name: 'l5', coef: prices[4] },
            { name: 'l6', coef: prices[5] },
            { name: 'l7', coef: prices[6] },
            { name: 'l8', coef: prices[7] },
        ]
    },
    subjectTo: [
        {
            name: 'SOC',
            vars: [
                { name: 'l1', coef: 1 },
                { name: 'l2', coef: 1 },
                { name: 'l3', coef: 1 },
                { name: 'l4', coef: 1 },
                { name: 'l5', coef: 1 },
                { name: 'l6', coef: 1 },
                { name: 'l7', coef: 1 },
                { name: 'l8', coef: 1 },
            ],
            bnds: { type: glpk.GLP_DB, ub: maxSoC, lb: minSoC }
        },
    ],
    bounds: [
        {
            name: 'l1',
            type: glpk.GLP_DB,
            ub: maxCharge,
            lb: minCharge
        },
        {
            name: 'l2',
            type: glpk.GLP_DB,
            ub: maxCharge,
            lb: minCharge
        },
        {
            name: 'l3',
            type: glpk.GLP_DB,
            ub: maxCharge,
            lb: minCharge
        },
        {
            name: 'l4',
            type: glpk.GLP_DB,
            ub: maxCharge,
            lb: minCharge
        },
        {
            name: 'l5',
            type: glpk.GLP_DB,
            ub: maxCharge,
            lb: minCharge
        },
        {
            name: 'l6',
            type: glpk.GLP_DB,
            ub: maxCharge,
            lb: minCharge
        },
        {
            name: 'l7',
            type: glpk.GLP_DB,
            ub: maxCharge,
            lb: minCharge
        },
        {
            name: 'l8',
            type: glpk.GLP_DB,
            ub: maxCharge,
            lb: minCharge
        }
    ]
}

const res = glpk.solve(toSolve, options);
```

**Comment by jvail** [comment]
I am not sure I understand the problem because since you do not set any minimum desired SoC in each period it would not charge at all or even go negative (minimization): which does not make sense but further minimizes the objective (negative costs).

Two ideas:
- Please take a look at other issues here. There were already several questions on negative variables https://github.com/jvail/glpk.js/issues?q=negativity

- Also isn't the state of charge in each period the sum of the states of all previous periods? So it seem you would need more constraints then just the one in `SOC`.

Maye it is better to consult the glpk mailing list or any other LP forum if you are stuck with modeling issues. I am certainly not an expert in  LP modeling.

**Comment by gruijter** [comment]
Thx for taking the time to respond (on Christmas day ;) ) !

Yes, I already figured I need to add constraints for each hour SoC. After adding that I got some nice results. Now I am figuring out how to use binaries for charge/discharge situation so I can add costs that depend on that (and also avoid negative variables).

Luctor et emergo... (I hope)

**Comment by jvail** [comment]
Sounds good! Frohe Weihnachten.
