### ISSUE TITLE
Obsolete

### ISSUE THREAD

**Issue by DmitryMyadzelets** [jvail/glpk.js#5]
Can't install under `node v10.x`.

This project inherites an issue from the [`node-glpk`](https://github.com/jvail/glpk.js) module: https://github.com/hgourvest/node-glpk/issues/6

**Comment by jvail** [comment]
Hi, I guess I need to remove node-glpk. I seems it is completely unmaintained...
But it is "just" a dev dept. So install should still be ok, right?

**Comment by jvail** [comment]
Thanks for providing a fix

**Comment by DmitryMyadzelets** [comment]
The `node-glpk` has been updated, and it's compatible with `nodejs` versions up to 11 now
