### ISSUE TITLE
can not use in angular

### ISSUE THREAD

**Issue by C4nf3ng** [jvail/glpk.js#7]
Module not found: Error: Can't resolve 'fs' in './node_modules/glpk.js'
Module not found: Error: Can't resolve 'path' ./node_modules/glpk.js'

**Comment by jvail** [comment]
If you add a bit of context, a snippet I can look into it. Maybe your import path is not correct? ....

**Comment by C4nf3ng** [comment]
I import and use glpk.js like this
> // @ts-ignore
> import glpkPromise from 'glpk.js'
> // @ts-ignore
> glpkPromise.then((glpk)=>(...))
> 
and got error 

> 
> WARNING in ./node_modules/glpk.js/glpk.js
> Module not found: Error: Can't resolve 'crypto' in './node_modules/glpk.js'
> 
> ERROR in ./node_modules/glpk.js/glpk.js
> Module not found: Error: Can't resolve 'fs' in './node_modules/glpk.js'
> ERROR in ./node_modules/glpk.js/glpk.js
> Module not found: Error: Can't resolve 'path' in './node_modules/glpk.js'
> 
>

**Comment by jvail** [comment]
I will try to setup a little angular app later. A quick guess: Actually I thought devs would use the glpk-worker.js for the browser and glpk.js for nodejs.
It seems like it is looking for missing libs usually available in nodejs (but not in the browser) - but emscripten does handle it already. For me it is not clear why it does look for those dependencies at all. If it is an error from webpack then maybe you can tell webpack to ignore any dependencies in glpk.js - there aren't any.

**Comment by C4nf3ng** [comment]
I finally make it import success by add 

>   "browser": {
>     "fs": false,
>     "path": false,
>     "crypto": false
>   }

to package.json 
but there are bugs in the package
1  in glpk.d.ts line 9-15 should be

>     subjectTo:
>         {
>             name: string,
>             vars: { name: string, coef: number }[],
>             bnds: { type: number, ub: number, lb: number }
>         }[],
rather than 

>     subjectTo:
>         [{
>             name: string,
>             vars: { name: string, coef: number }[],
>             bnds: { type: number, ub: number, lb: number }
>         }[]],

when i fix this bug another bug comes out 

> glp_set_mat_row: i = 1; ind[2] = 1; duplicate column indices not allowed
> glpk.js:1042 Error detected in file ../../src/api/prob1.c at line 779
> glpk.js:665 undefined
> glpk.js:666 undefined
> abort @ glpk.js:666
> _abort @ glpk.js:3372
> (anonymous) @ glpk.wasm:1
> (anonymous) @ glpk.wasm:1
> push../node_modules/glpk.js/glpk.js.Module._glp_set_mat_row @ glpk.js:3572
> (anonymous) @ glpk.js:144
> setup @ glpk.js:124
> solve @ glpk.js:85

i checked the code that call glp_set_mat_row

> glp_set_mat_row(P, row, vars.length, ind_ptr, val_ptr);

however i found that the c definition of glp_set_mat_row is

> void glp_set_mat_row(glp_prob *lp, int i, int len, const int ind[], const double val[]);

the args in this library seems wrong

**Comment by jvail** [comment]
I fixed the types - thanks for reporting. I setup a branch 'angular' with a solution that seems to work:

- copy the wasm in the assets section
- include glpk as script in angular.json

I think I need to dig a bit into the latest emscripten api to find a better solution for ordinary imports. 

I have never had an issue with the c api and did not change it for a long time. I'd guess you have an issue with "duplicate column indices not allowed" i.e. duplicate variable names.
