### ISSUE TITLE
Document how to define variable types

### ISSUE THREAD

**Issue by mancontr** [jvail/glpk.js#8]
Currently there is no indications on how to set the variable type, even if there are some constants related to it (`GLP_CV`, `GLP_IV`, `GLP_BV`).

Peeking at the code I noticed that we can set `lp.binaries` to an array of variable names to set them as binary, but I think that this should be added to the README, along with how to set them as integer.

Thanks for the great library!

**Comment by jvail** [comment]
Thanks for reporting. You are right. Those constants are part of the api but useless. And the "generals" are also missing in the type ... not good.

So, I guess 

* removing GLP_CV, GLP_IV, GLP_BV from the api 
* adding generals to the LP interface
* adding a complete example including "generals" and "binaries"

should fix it?

**Comment by mancontr** [comment]
Yes, I think that would fix it

**Comment by mancontr** [comment]
Thanks for the quick fix! 

I just noticed that there is another option for setting the variable ranges too:
```
lp.bounds = [
    { name: 'x1', type: glpk.GLP_DB, lb: 0, ub: 10 }
]
```

I think it would be useful to add it to the readme too.

**Comment by jvail** [comment]
Hi @mancontr, yes, again, you are right :) The documentation is really minimal. There are examples and tests and a few lines of source code so I thought everyone could easily figure out what to do. But certainly more docu would be nice. Would you like to make a suggestion and a PR? I'll be happy to review and merge it.
